---
# Modified from https://github.com/microservices-demo/microservices-demo
# Please see this repository for the original

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  labels:
    name: carts
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: carts
  template:
    metadata:
      labels:
        name: carts
    spec:
      containers:
      - name: carts
        image: weaveworksdemos/carts:0.4.8
        ports:
        - containerPort: 80
        command:
        - java
        - -Djava.security.egd=file:/dev/urandom
        - -Dspring.data.mongodb.uri=mongodb://mongodb-0:27017/data?replicaSet=rs0
        - -jar
        - ./app.jar
        - --port=80
